## Intro To Pandas

In [1]:
import numpy as np
import pandas as pd

## Series

A series is a 1D array with axis labels which we use as the index (similar to one column in a table)

In [2]:
#Creating a series from the list 
x = pd.Series([5,10,15,20,25])
x

0     5
1    10
2    15
3    20
4    25
dtype: int64

In [3]:
#Accessing the index
x.index

RangeIndex(start=0, stop=5, step=1)

In [4]:
##Accessing the values
x.values

array([ 5, 10, 15, 20, 25])

In [5]:
#Looking at data type in our series 
x.dtype

dtype('int64')

In [6]:
#Creating a Series with a custom index
data = [350,400,450]
Sales = pd.Series(data, index=["Ivy", "Mike", "Edwin"])
Sales

Ivy      350
Mike     400
Edwin    450
dtype: int64

In [7]:
#Check the type
type(Sales)

In [8]:
#A Series is the pandas type shown by type(Sales)
pd.Series

In [9]:
Sales.index

Index(['Ivy', 'Mike', 'Edwin'], dtype='object')

## Accessing Values

In [10]:
#Using index Names
Sales["Ivy"]

np.int64(350)

## Checking for conditions

We can filter data to select values that meet a condition.

In [11]:
Sales > 400

Ivy      False
Mike     False
Edwin     True
dtype: bool

In [12]:
Sales [[False, False, True]]

Edwin    450
dtype: int64

In [13]:
Sales[Sales > 400]

Edwin    450
dtype: int64

In [14]:
#Checking names in index
"Ivy" in Sales

True

In [15]:
#False output for above e.g
"Jimmy" in Sales

False

In [16]:
#The reason it's false is because 450 is a value however IN checks the index not value
450 in Sales

False

## Working with Dictionaries

In [17]:
##Converting a series into a Python dictionary 
sales_dict = Sales.to_dict()
sales_dict

{'Ivy': 350, 'Mike': 400, 'Edwin': 450}

In [18]:
sales_ser = pd.Series (sales_dict)
sales_ser

Ivy      350
Mike     400
Edwin    450
dtype: int64

## Adding entries and working with NULL values (NaN)

In [19]:
##We can create a new Series from an already existing series 
new_sales = pd.Series (Sales, index = ["Ivy","Mike", "Edwin", "Jacob", "Maya"])
new_sales

Ivy      350.0
Mike     400.0
Edwin    450.0
Jacob      NaN
Maya       NaN
dtype: float64

In [20]:
#Checking for NULL values
print(np.isnan(new_sales["Maya"]))

True

In [21]:
#NaN represents a missing numeric value; it is not the same as None
new_sales["Maya"] is None

False

In [22]:
#Check the entire Series for missing values using pd.isnull()
pd.isnull(new_sales)

Ivy      False
Mike     False
Edwin    False
Jacob     True
Maya      True
dtype: bool

In [23]:
#Naming an Index
Sales.index.name = "Sales Person"
Sales

Sales Person
Ivy      350
Mike     400
Edwin    450
dtype: int64

In [24]:
#Naming a series
Sales.name = "Total Car Sales"
Sales

Sales Person
Ivy      350
Mike     400
Edwin    450
Name: Total Car Sales, dtype: int64

## DataFrames

DataFrames are 2D, size-mutable, potentially heterogeneous (diverse) tabular data structures. This data structure contains labeled axes (rows and columns).

In [25]:
#Creating a DataFrame from a list of lists
df_data = [["Adrian", 20], ["Max", 23], ["Jax", 41]]

#Provide the column names in the same order as the data
df = pd.DataFrame(df_data, columns=["Name", "Age"])

In [26]:
df

     Name  Age
0  Adrian   20
1     Max   23
2     Jax   41

In [27]:
# Creating a DataFrame from a dictionary 
new_dict2 = {'Name':['Tom','Jane','Steve','Lucy'],'Sales':[250,300,350,400]}

df_dict = pd.DataFrame(new_dict2)
df_dict

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [28]:
##Adding a custom index
df_dict_index = pd.DataFrame(new_dict2, index = ["Rank 1", "Rank 2", "Rank 3", "Rank 4"])

df_dict_index

         Name  Sales
Rank 1    Tom    250
Rank 2   Jane    300
Rank 3  Steve    350
Rank 4   Lucy    400

In [29]:
# Creating a DataFrame from a list of Dictionaries # This is the same data as we had previously, but in a different format
# This is useful when working with JSON
dict_list = [{'Name':'Tom','Sales':250},{'Name':'Jane','Sales':300},{'Name':'Steve','Sales':350},{'Name':'Lucy','Sales':400}]

df_dict_list = pd.DataFrame(dict_list)
df_dict_list

    Name  Sales
0    Tom    250
1   Jane    300
2  Steve    350
3   Lucy    400

In [30]:
#Creating a DataFrame from a dictionary of series 

east = pd.Series ([1000, 1200, 3400], index =["Q1", "Q2", "Q3"])

east

Q1    1000
Q2    1200
Q3    3400
dtype: int64

In [31]:
west = pd.Series ([1100, 1300, 2400,3500], index =["Q1", "Q2", "Q3", "Q4"])

west

Q1    1100
Q2    1300
Q3    2400
Q4    3500
dtype: int64

In [32]:
## We can combine our series to create a brand new DataFrame containing both 

df_region = pd.DataFrame({"East":east, "West":west})

df_region

      East  West
Q1  1000.0  1100
Q2  1200.0  1300
Q3  3400.0  2400
Q4     NaN  3500

In [33]:
#We can add new series into our DataFrame after we have created it!

df_region ["North"] = [2000, 3000, 2500, 4000]

df_region ["South"] = [1500, 2000, 1500, 4000]

df_region

      East  West  North  South
Q1  1000.0  1100   2000   1500
Q2  1200.0  1300   3000   2000
Q3  3400.0  2400   2500   1500
Q4     NaN  3500   4000   4000

In [34]:
#Add a Years column to the DataFrame
years = ["2016", "2017", "2018", "2019"]

df_region["Years"] = years

df_region

      East  West  North  South Years
Q1  1000.0  1100   2000   1500  2016
Q2  1200.0  1300   3000   2000  2017
Q3  3400.0  2400   2500   1500  2018
Q4     NaN  3500   4000   4000  2019

In [35]:
#Set the Years column as the index, replacing the quarters (Q1 etc.)
df_region = df_region.set_index("Years")

df_region

         East  West  North  South
Years
2016   1000.0  1100   2000   1500
2017   1200.0  1300   3000   2000
2018   3400.0  2400   2500   1500
2019      NaN  3500   4000   4000

In [36]:
#Reindex the rows and add two new years with NaN values
re_indexed = df_region.reindex(["2016", "2017", "2018", "2019", "2020", "2021"])

#Keep new_df available for the next examples
new_df = re_indexed.copy()

re_indexed

         East    West   North   South
Years
2016   1000.0  1100.0  2000.0  1500.0
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019      NaN  3500.0  4000.0  4000.0
2020      NaN     NaN     NaN     NaN
2021      NaN     NaN     NaN     NaN

## Handling Missing Data

In [37]:
#Filling in missing values
#Some algorithms cannot handle NaN values
#Display missing values replaced with 0 without changing re_indexed
re_indexed.fillna(0)

         East    West   North   South
Years
2016   1000.0  1100.0  2000.0  1500.0
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019      0.0  3500.0  4000.0  4000.0
2020      0.0     0.0     0.0     0.0
2021      0.0     0.0     0.0     0.0

In [38]:
#Forward fill: carry the previous available value down each column
#Backward fill uses the next available value instead: re_indexed.bfill()
#This displays the result without changing re_indexed
re_indexed.ffill()

         East    West   North   South
Years
2016   1000.0  1100.0  2000.0  1500.0
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019   3400.0  3500.0  4000.0  4000.0
2020   3400.0  3500.0  4000.0  4000.0
2021   3400.0  3500.0  4000.0  4000.0

In [39]:
#Linear interpolation estimates missing values between known values
#By default, trailing gaps are filled with the last available value
re_indexed.interpolate()

         East    West   North   South
Years
2016   1000.0  1100.0  2000.0  1500.0
2017   1200.0  1300.0  3000.0  2000.0
2018   3400.0  2400.0  2500.0  1500.0
2019   3400.0  3500.0  4000.0  4000.0
2020   3400.0  3500.0  4000.0  4000.0
2021   3400.0  3500.0  4000.0  4000.0

## Dropping Items in DataFrames