## Working with a dataset

In [1]:
import numpy as np
import pandas as pd

### CSV files in Pandas

Download the iris dataset via the terminal using - it has to be in the same directory as where the notebook is stored

curl -L bit.ly/sparta_iris > iris.csv

In [2]:
#Load the CSV into a DataFrame
iris = pd.read_csv("iris.csv")

#Display the first 5 rows
iris.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Writing a DataFrame to CSV

Calling .to_csv() saves a DataFrame as a CSV file.

index= False - this prevents the row index from being saved as an extra column.

In [3]:
#Save the DataFrame to a new CSV file

iris.to_csv("iris_2.csv", index=False)

In [4]:
#Read the saved CSV

iris_2 = pd.read_csv("iris_2.csv")
iris_2.head()

   sepal_length  sepal_width  petal_length  petal_width species
0           5.1          3.5           1.4          0.2  setosa
1           4.9          3.0           1.4          0.2  setosa
2           4.7          3.2           1.3          0.2  setosa
3           4.6          3.1           1.5          0.2  setosa
4           5.0          3.6           1.4          0.2  setosa

### Grouping Data

.groupby() groups rows with matching values in a column.

Here, we group by species and calculate the mean of each numerical column.

In [5]:
#Calc mean for each species

iris.groupby("species").mean()

            sepal_length  sepal_width  petal_length  petal_width
species
setosa             5.006        3.418         1.464        0.244
versicolor         5.936        2.770         4.260        1.326
virginica          6.588        2.974         5.552        2.026

### Iterating Through the Data

.iterrows() loops through a DataFrame one row at a time.

It provides the row index and the row’s values.

In [8]:
#Loop through each row and display its values
for i, row in iris.iterrows():
    
    print(row)

sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.2
species         setosa
Name: 0, dtype: object
sepal_length       4.9
sepal_width        3.0
petal_length       1.4
petal_width        0.2
species         setosa
Name: 1, dtype: object
sepal_length       4.7
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 2, dtype: object
sepal_length       4.6
sepal_width        3.1
petal_length       1.5
petal_width        0.2
species         setosa
Name: 3, dtype: object
sepal_length       5.0
sepal_width        3.6
petal_length       1.4
petal_width        0.2
species         setosa
Name: 4, dtype: object
sepal_length       5.4
sepal_width        3.9
petal_length       1.7
petal_width        0.4
species         setosa
Name: 5, dtype: object
sepal_length       4.6
sepal_width        3.4
petal_length       1.4
petal_width        0.3
species         setosa
Name: 6, dtype: object
sepal_length       5.0
sepal_width        3.4
petal_length       1.5
petal_width        0.2
species         setosa
Name: 7, dtype: object
sepal_length       4.4
sepal_width        2.9
petal_length       1.4
petal_width        0.2
species         setosa
Name: 8, dtype: object
sepal_length       4.9
sepal_width        3.1
petal_length       1.5
petal_width        0.1
species         setosa
Name: 9, dtype: object
sepal_length       5.4
sepal_width        3.7
petal_length       1.5
petal_width        0.2
species         setosa
Name: 10, dtype: object
sepal_length       4.8
sepal_width        3.4
petal_length       1.6
petal_width        0.2
species         setosa
Name: 11, dtype: object
sepal_length       4.8
sepal_width        3.0
petal_length       1.4
petal_width        0.1
species         setosa
Name: 12, dtype: object
sepal_length       4.3
sepal_width        3.0
petal_length       1.1
petal_width        0.1
species         setosa
Name: 13, dtype: object
sepal_length       5.8
sepal_width        4.0
petal_length       1.2
petal_width        0.2
species         setosa
Name: 14, dtype: object
sepal_length       5.7
sepal_width        4.4
petal_length       1.5
petal_width        0.4
species         setosa
Name: 15, dtype: object
sepal_length       5.4
sepal_width        3.9
petal_length       1.3
petal_width        0.4
species         setosa
Name: 16, dtype: object
sepal_length       5.1
sepal_width        3.5
petal_length       1.4
petal_width        0.3
species         setosa
Name: 17, dtype: object
sepal_length       5.7
sepal_width        3.8
petal_length       1.7
petal_width        0.3
species         setosa
Name: 18, dtype: object
sepal_length       5.1
sepal_width        3.8
petal_length       1.5
petal_width        0.3
species         setosa
Name: 19, dtype: object
sepal_length       5.4
sepal_width        3.4
petal_length       1.7
petal_width        0.2
species         setosa
Name: 20, dtype: object
sepal_length       5.1
sepal_width        3.7
petal_length       1.5
petal_width        0.4
species         setosa
Name: 21, dtype: object
sepal_length       4.6
sepal_width        3.6
petal_length       1.0
petal_width        0.2
species         setosa
Name: 22, dtype: object
sepal_length       5.1
sepal_width        3.3
petal_length       1.7
petal_width        0.5
species         setosa
Name: 23, dtype: object
sepal_length       4.8
sepal_width        3.4
petal_length       1.9
petal_width        0.2
species         setosa
Name: 24, dtype: object
sepal_length       5.0
sepal_width        3.0
petal_length       1.6
petal_width        0.2
species         setosa
Name: 25, dtype: object
sepal_length       5.0
sepal_width        3.4
petal_length       1.6
petal_width        0.4
species         setosa
Name: 26, dtype: object
sepal_length       5.2
sepal_width        3.5
petal_length       1.5
petal_width        0.2
species         setosa
Name: 27, dtype: object
sepal_length       5.2
sepal_width        3.4
petal_length       1.4
petal_width        0.2
species         setosa
Name: 28, dtype: object
sepal_length       4.7
sepal_width        3.2
petal_length       1.6
petal_width        0.2
species         setosa
Name: 29, dtype: object
sepal_length       4.8
sepal_width        3.1
petal_length       1.6
petal_width        0.2
species         setosa
Name: 30, dtype: object
sepal_length       5.4
sepal_width        3.4
petal_length       1.5
petal_width        0.4
species         setosa
Name: 31, dtype: object
sepal_length       5.2
sepal_width        4.1
petal_length       1.5
petal_width        0.1
species         setosa
Name: 32, dtype: object
sepal_length       5.5
sepal_width        4.2
petal_length       1.4
petal_width        0.2
species         setosa
Name: 33, dtype: object
sepal_length       4.9
sepal_width        3.1
petal_length       1.5
petal_width        0.1
species         setosa
Name: 34, dtype: object
sepal_length       5.0
sepal_width        3.2
petal_length       1.2
petal_width        0.2
species         setosa
Name: 35, dtype: object
sepal_length       5.5
sepal_width        3.5
petal_length       1.3
petal_width        0.2
species         setosa
Name: 36, dtype: object
sepal_length       4.9
sepal_width        3.1
petal_length       1.5
petal_width        0.1
species         setosa
Name: 37, dtype: object
sepal_length       4.4
sepal_width        3.0
petal_length       1.3
petal_width        0.2
species         setosa
Name: 38, dtype: object
sepal_length       5.1
sepal_width        3.4
petal_length       1.5
petal_width        0.2
species         setosa
Name: 39, dtype: object
sepal_length       5.0
sepal_width        3.5
petal_length       1.3
petal_width        0.3
species         setosa
Name: 40, dtype: object
sepal_length       4.5
sepal_width        2.3
petal_length       1.3
petal_width        0.3
species         setosa
Name: 41, dtype: object
sepal_length       4.4
sepal_width        3.2
petal_length       1.3
petal_width        0.2
species         setosa
Name: 42, dtype: object
sepal_length       5.0
sepal_width        3.5
petal_length       1.6
petal_width        0.6
species         setosa
Name: 43, dtype: object
sepal_length       5.1
sepal_width        3.8
petal_length       1.9
petal_width        0.4
species         setosa
Name: 44, dtype: object
sepal_length       4.8
sepal_width        3.0
petal_length       1.4
petal_width        0.3
species         setosa
Name: 45, dtype: object
sepal_length       5.1
sepal_width        3.8
petal_length       1.6
petal_width        0.2
species         setosa
Name: 46, dtype: object
sepal_length       4.6
sepal_width        3.2
petal_length       1.4
petal_width        0.2
species         setosa
Name: 47, dtype: object
sepal_length       5.3
sepal_width        3.7
petal_length       1.5
petal_width        0.2
species         setosa
Name: 48, dtype: object
sepal_length       5.0
sepal_width        3.3
petal_length       1.4
petal_width        0.2
species         setosa
Name: 49, dtype: object
sepal_length           7.0
sepal_width            3.2
petal_length           4.7
petal_width            1.4
species         versicolor
Name: 50, dtype: object
sepal_length           6.4
sepal_width            3.2
petal_length           4.5
petal_width            1.5
species         versicolor
Name: 51, dtype: object
sepal_length           6.9
sepal_width            3.1
petal_length           4.9
petal_width            1.5
species         versicolor
Name: 52, dtype: object
sepal_length           5.5
sepal_width            2.3
petal_length           4.0
petal_width            1.3
species         versicolor
Name: 53, dtype: object
sepal_length           6.5
sepal_width            2.8
petal_length           4.6
petal_width            1.5
species         versicolor
Name: 54, dtype: object
sepal_length           5.7
sepal_width            2.8
petal_length           4.5
petal_width            1.3
species         versicolor
Name: 55, dtype: object
sepal_length           6.3
sepal_width            3.3
petal_length           4.7
petal_width            1.6
species         versicolor
Name: 56, dtype: object
sepal_length           4.9
sepal_width            2.4
petal_length           3.3
petal_width            1.0
species         versicolor
Name: 57, dtype: object
sepal_length           6.6
sepal_width            2.9
petal_length           4.6
petal_width            1.3
species         versicolor
Name: 58, dtype: object
sepal_length           5.2
sepal_width            2.7
petal_length           3.9
petal_width            1.4
species         versicolor
Name: 59, dtype: object
sepal_length           5.0
sepal_width            2.0
petal_length           3.5
petal_width            1.0
species         versicolor
Name: 60, dtype: object
sepal_length           5.9
sepal_width            3.0
petal_length           4.2
petal_width            1.5
species         versicolor
Name: 61, dtype: object
sepal_length           6.0
sepal_width            2.2
petal_length           4.0
petal_width            1.0
species         versicolor
Name: 62, dtype: object
sepal_length           6.1
sepal_width            2.9
petal_length           4.7
petal_width            1.4
species         versicolor
Name: 63, dtype: object
sepal_length           5.6
sepal_width            2.9
petal_length           3.6
petal_width            1.3
species         versicolor
Name: 64, dtype: object
sepal_length           6.7
sepal_width            3.1
petal_length           4.4
petal_width            1.4
species         versicolor
Name: 65, dtype: object
sepal_length           5.6
sepal_width            3.0
petal_length           4.5
petal_width            1.5
species         versicolor
Name: 66, dtype: object
sepal_length           5.8
sepal_width            2.7
petal_length           4.1
petal_width            1.0
species         versicolor
Name: 67, dtype: object
sepal_length           6.2
sepal_width            2.2
petal_length           4.5
petal_width            1.5
species         versicolor
Name: 68, dtype: object
sepal_length           5.6
sepal_width            2.5
petal_length           3.9
petal_width            1.1
species         versicolor
Name: 69, dtype: object
sepal_length           5.9
sepal_width            3.2
petal_length           4.8
petal_width            1.8
species         versicolor
Name: 70, dtype: object
sepal_length           6.1
sepal_width            2.8
petal_length           4.0
petal_width            1.3
species         versicolor
Name: 71, dtype: object
sepal_length           6.3
sepal_width            2.5
petal_length           4.9
petal_width            1.5
species         versicolor
Name: 72, dtype: object
sepal_length           6.1
sepal_width            2.8
petal_length           4.7
petal_width            1.2
species         versicolor
Name: 73, dtype: object
sepal_length           6.4
sepal_width            2.9
petal_length           4.3
petal_width            1.3
species         versicolor
Name: 74, dtype: object
sepal_length           6.6
sepal_width            3.0
petal_length           4.4
petal_width            1.4
species         versicolor
Name: 75, dtype: object
sepal_length           6.8
sepal_width            2.8
petal_length           4.8
petal_width            1.4
species         versicolor
Name: 76, dtype: object
sepal_length           6.7
sepal_width            3.0
petal_length           5.0
petal_width            1.7
species         versicolor
Name: 77, dtype: object
sepal_length           6.0
sepal_width            2.9
petal_length           4.5
petal_width            1.5
species         versicolor
Name: 78, dtype: object
sepal_length           5.7
sepal_width            2.6
petal_length           3.5
petal_width            1.0
species         versicolor
Name: 79, dtype: object
sepal_length           5.5
sepal_width            2.4
petal_length           3.8
petal_width            1.1
species         versicolor
Name: 80, dtype: object
sepal_length           5.5
sepal_width            2.4
petal_length           3.7
petal_width            1.0
species         versicolor
Name: 81, dtype: object
sepal_length           5.8
sepal_width            2.7
petal_length           3.9
petal_width            1.2
species         versicolor
Name: 82, dtype: object
sepal_length           6.0
sepal_width            2.7
petal_length           5.1
petal_width            1.6
species         versicolor
Name: 83, dtype: object
sepal_length           5.4
sepal_width            3.0
petal_length           4.5
petal_width            1.5
species         versicolor
Name: 84, dtype: object
sepal_length           6.0
sepal_width            3.4
petal_length           4.5
petal_width            1.6
species         versicolor
Name: 85, dtype: object
sepal_length           6.7
sepal_width            3.1
petal_length           4.7
petal_width            1.5
species         versicolor
Name: 86, dtype: object
sepal_length           6.3
sepal_width            2.3
petal_length           4.4
petal_width            1.3
species         versicolor
Name: 87, dtype: object
sepal_length           5.6
sepal_width            3.0
petal_length           4.1
petal_width            1.3
species         versicolor
Name: 88, dtype: object
sepal_length           5.5
sepal_width            2.5
petal_length           4.0
petal_width            1.3
species         versicolor
Name: 89, dtype: object
sepal_length           5.5
sepal_width            2.6
petal_length           4.4
petal_width            1.2
species         versicolor
Name: 90, dtype: object
sepal_length           6.1
sepal_width            3.0
petal_length           4.6
petal_width            1.4
species         versicolor
Name: 91, dtype: object
sepal_length           5.8
sepal_width            2.6
petal_length           4.0
petal_width            1.2
species         versicolor
Name: 92, dtype: object
sepal_length           5.0
sepal_width            2.3
petal_length           3.3
petal_width            1.0
species         versicolor
Name: 93, dtype: object
sepal_length           5.6
sepal_width            2.7
petal_length           4.2
petal_width            1.3
species         versicolor
Name: 94, dtype: object
sepal_length           5.7
sepal_width            3.0
petal_length           4.2
petal_width            1.2
species         versicolor
Name: 95, dtype: object
sepal_length           5.7
sepal_width            2.9
petal_length           4.2
petal_width            1.3
species         versicolor
Name: 96, dtype: object
sepal_length           6.2
sepal_width            2.9
petal_length           4.3
petal_width            1.3
species         versicolor
Name: 97, dtype: object
sepal_length           5.1
sepal_width            2.5
petal_length           3.0
petal_width            1.1
species         versicolor
Name: 98, dtype: object
sepal_length           5.7
sepal_width            2.8
petal_length           4.1
petal_width            1.3
species         versicolor
Name: 99, dtype: object
sepal_length          6.3
sepal_width           3.3
petal_length          6.0
petal_width           2.5
species         virginica
Name: 100, dtype: object
sepal_length          5.8
sepal_width           2.7
petal_length          5.1
petal_width           1.9
species         virginica
Name: 101, dtype: object
sepal_length          7.1
sepal_width           3.0
petal_length          5.9
petal_width           2.1
species         virginica
Name: 102, dtype: object
sepal_length          6.3
sepal_width           2.9
petal_length          5.6
petal_width           1.8
species         virginica
Name: 103, dtype: object
sepal_length          6.5
sepal_width           3.0
petal_length          5.8
petal_width           2.2
species         virginica
Name: 104, dtype: object
sepal_length          7.6
sepal_width           3.0
petal_length          6.6
petal_width           2.1
species         virginica
Name: 105, dtype: object
sepal_length          4.9
sepal_width           2.5
petal_length          4.5
petal_width           1.7
species         virginica
Name: 106, dtype: object
sepal_length          7.3
sepal_width           2.9
petal_length          6.3
petal_width           1.8
species         virginica
Name: 107, dtype: object
sepal_length          6.7
sepal_width           2.5
petal_length          5.8
petal_width           1.8
species         virginica
Name: 108, dtype: object
sepal_length          7.2
sepal_width           3.6
petal_length          6.1
petal_width           2.5
species         virginica
Name: 109, dtype: object
sepal_length          6.5
sepal_width           3.2
petal_length          5.1
petal_width           2.0
species         virginica
Name: 110, dtype: object
sepal_length          6.4
sepal_width           2.7
petal_length          5.3
petal_width           1.9
species         virginica
Name: 111, dtype: object
sepal_length          6.8
sepal_width           3.0
petal_length          5.5
petal_width           2.1
species         virginica
Name: 112, dtype: object
sepal_length          5.7
sepal_width           2.5
petal_length          5.0
petal_width           2.0
species         virginica
Name: 113, dtype: object
sepal_length          5.8
sepal_width           2.8
petal_length          5.1
petal_width           2.4
species         virginica
Name: 114, dtype: object
sepal_length          6.4
sepal_width           3.2
petal_length          5.3
petal_width           2.3
species         virginica
Name: 115, dtype: object
sepal_length          6.5
sepal_width           3.0
petal_length          5.5
petal_width           1.8
species         virginica
Name: 116, dtype: object
sepal_length          7.7
sepal_width           3.8
petal_length          6.7
petal_width           2.2
species         virginica
Name: 117, dtype: object
sepal_length          7.7
sepal_width           2.6
petal_length          6.9
petal_width           2.3
species         virginica
Name: 118, dtype: object
sepal_length          6.0
sepal_width           2.2
petal_length          5.0
petal_width           1.5
species         virginica
Name: 119, dtype: object
sepal_length          6.9
sepal_width           3.2
petal_length          5.7
petal_width           2.3
species         virginica
Name: 120, dtype: object
sepal_length          5.6
sepal_width           2.8
petal_length          4.9
petal_width           2.0
species         virginica
Name: 121, dtype: object
sepal_length          7.7
sepal_width           2.8
petal_length          6.7
petal_width           2.0
species         virginica
Name: 122, dtype: object
sepal_length          6.3
sepal_width           2.7
petal_length          4.9
petal_width           1.8
species         virginica
Name: 123, dtype: object
sepal_length          6.7
sepal_width           3.3
petal_length          5.7
petal_width           2.1
species         virginica
Name: 124, dtype: object
sepal_length          7.2
sepal_width           3.2
petal_length          6.0
petal_width           1.8
species         virginica
Name: 125, dtype: object
sepal_length          6.2
sepal_width           2.8
petal_length          4.8
petal_width           1.8
species         virginica
Name: 126, dtype: object
sepal_length          6.1
sepal_width           3.0
petal_length          4.9
petal_width           1.8
species         virginica
Name: 127, dtype: object
sepal_length          6.4
sepal_width           2.8
petal_length          5.6
petal_width           2.1
species         virginica
Name: 128, dtype: object
sepal_length          7.2
sepal_width           3.0
petal_length          5.8
petal_width           1.6
species         virginica
Name: 129, dtype: object
sepal_length          7.4
sepal_width           2.8
petal_length          6.1
petal_width           1.9
species         virginica
Name: 130, dtype: object
sepal_length          7.9
sepal_width           3.8
petal_length          6.4
petal_width           2.0
species         virginica
Name: 131, dtype: object
sepal_length          6.4
sepal_width           2.8
petal_length          5.6
petal_width           2.2
species         virginica

### Summarising the Data

.describe() shows the count, mean, standard deviation, minimum,
quartiles and maximum for each numerical column.

In [9]:
iris.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.054000      3.758667     1.198667
std        0.828066     0.433594      1.764420     0.763161
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

### Ranking Petal Length

.rank(ascending=True) ranks petal lengths from smallest to largest.
Equal values receive the average of their rank positions.

In [10]:
#Add a rank column for petal length

iris["petal_rank"] = iris["petal_length"].rank(ascending = True)

iris.head()

   sepal_length  sepal_width  petal_length  petal_width species  petal_rank
0           5.1          3.5           1.4          0.2  setosa        17.5
1           4.9          3.0           1.4          0.2  setosa        17.5
2           4.7          3.2           1.3          0.2  setosa         8.0
3           4.6          3.1           1.5          0.2  setosa        30.5
4           5.0          3.6           1.4          0.2  setosa        17.5

### Creating a DataFrame for Each Species

Filter the species column to create separate DataFrames for
setosa, versicolor and virginica.

In [12]:
#Find the species names in the dataset
iris["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [11]:
#Create a separate DataFrame for each species - .copy() lets us work with each new DataFrame independently.
setosa = iris[iris["species"] == "setosa"].copy()

versicolor = iris[iris["species"] == "versicolor"].copy()

virginica = iris[iris["species"] == "virginica"].copy()

In [13]:
setosa.head()

   sepal_length  sepal_width  petal_length  petal_width species  petal_rank
0           5.1          3.5           1.4          0.2  setosa        17.5
1           4.9          3.0           1.4          0.2  setosa        17.5
2           4.7          3.2           1.3          0.2  setosa         8.0
3           4.6          3.1           1.5          0.2  setosa        30.5
4           5.0          3.6           1.4          0.2  setosa        17.5

In [14]:
versicolor.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_rank
50,7.0,3.2,4.7,1.4,versicolor,93.0
51,6.4,3.2,4.5,1.5,versicolor,83.5
52,6.9,3.1,4.9,1.5,versicolor,102.0
53,5.5,2.3,4.0,1.3,versicolor,64.0
54,6.5,2.8,4.6,1.5,versicolor,89.0

In [15]:
virginica.head()

,sepal_length,sepal_width,petal_length,petal_width,species,petal_rank
100,6.3,3.3,6.0,2.5,virginica,140.5
101,5.8,2.7,5.1,1.9,virginica,112.5
102,7.1,3.0,5.9,2.1,virginica,138.5
103,6.3,2.9,5.6,1.8,virginica,128.5
104,6.5,3.0,5.8,2.2,virginica,136.0

### Separating Sepal and Petal Data


Create 2 final df, one for sepal info and one for petal info (with data from all three species in each)

We will select the relevant columns for each DataFrame & keep the species column so each flower can still be identified.

In [19]:
#Create a DataFrame containing sepal measurements

sepal_df = iris[["sepal_length", "sepal_width", "species"]].copy()

sepal_df

     sepal_length  sepal_width    species
0             5.1          3.5     setosa
1             4.9          3.0     setosa
2             4.7          3.2     setosa
3             4.6          3.1     setosa
4             5.0          3.6     setosa
..            ...          ...        ...
145           6.7          3.0  virginica
146           6.3          2.5  virginica
147           6.5          3.0  virginica
148           6.2          3.4  virginica
149           5.9          3.0  virginica

[150 rows x 3 columns]

In [18]:
#Create a DataFrame containing petal measurements 

#Double brackets [[...]] select multiple columns. Both DataFrames retain every row, so they include all three species.

petal_df = iris[["petal_length", "petal_width", "species"]].copy()

petal_df

     petal_length  petal_width    species
0             1.4          0.2     setosa
1             1.4          0.2     setosa
2             1.3          0.2     setosa
3             1.5          0.2     setosa
4             1.4          0.2     setosa
..            ...          ...        ...
145           5.2          2.3  virginica
146           5.0          1.9  virginica
147           5.2          2.0  virginica
148           5.4          2.3  virginica
149           5.1          1.8  virginica

[150 rows x 3 columns]

In [20]:
sepal_df["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [21]:
petal_df["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

## JSON Files and Pandas

JSON stores data using key-value pairs.

pd.read_json() loads a JSON file into a DataFrame.

In [24]:
#Load the JSON file
iris_json = pd.read_json("iris.json")

#Display the first 5 rows
iris_json.head()

   sepalLength  sepalWidth  petalLength  petalWidth species
0          5.1         3.5          1.4         0.2  setosa
1          4.9         3.0          1.4         0.2  setosa
2          4.7         3.2          1.3         0.2  setosa
3          4.6         3.1          1.5         0.2  setosa
4          5.0         3.6          1.4         0.2  setosa

## Merging DataFrames

pd.merge() combines DataFrames using matching columns or indexes.

Here, the original row indexes match the sepal and petal measurements
for each flower.

In [25]:
#Merge the DataFrames using their original row indexes

merged_df = pd.merge(
    sepal_df,
    petal_df,
    left_index=True,
    right_index=True
)

merged_df.head()

   sepal_length  sepal_width species_x  petal_length  petal_width species_y
0           5.1          3.5    setosa           1.4          0.2    setosa
1           4.9          3.0    setosa           1.4          0.2    setosa
2           4.7          3.2    setosa           1.3          0.2    setosa
3           4.6          3.1    setosa           1.5          0.2    setosa
4           5.0          3.6    setosa           1.4          0.2    setosa

### Removing the Repeated Column

Both DataFrames contained species, so the merge created species_x
and species_y. Drop species_y and rename species_x to species.

In [30]:
#Drop the repeated species column
merged_df = merged_df.drop(columns=["species_y"])

#Rename the remaining species column
merged_df = merged_df.rename(columns={"species_x": "species"})

merged_df.head()

   sepal_length  sepal_width species  petal_length  petal_width
0           5.1          3.5  setosa           1.4          0.2
1           4.9          3.0  setosa           1.4          0.2
2           4.7          3.2  setosa           1.3          0.2
3           4.6          3.1  setosa           1.5          0.2
4           5.0          3.6  setosa           1.4          0.2

## Concatenation

pd.concat() combines DataFrames along rows or columns.

This combines the three species DataFrames back into one DataFrame.

ignore_index = True creates a new row index starting at 0.

In [31]:
#where n is the total number of rows

#Combine all three species into one DataFrame
iris_combined = pd.concat(
    [setosa, versicolor, virginica],
    ignore_index=True
)

iris_combined.head()

   sepal_length  sepal_width  petal_length  petal_width species  petal_rank
0           5.1          3.5           1.4          0.2  setosa        17.5
1           4.9          3.0           1.4          0.2  setosa        17.5
2           4.7          3.2           1.3          0.2  setosa         8.0
3           4.6          3.1           1.5          0.2  setosa        30.5
4           5.0          3.6           1.4          0.2  setosa        17.5

In [32]:
#Check that all three species are present:
iris_combined["species"].unique()

<StringArray>
['setosa', 'versicolor', 'virginica']
Length: 3, dtype: str

In [33]:
#Count the rows for each species
iris_combined["species"].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64